name: "📖 History Form"
description: Project History
title: "[Digite o Título da História]"
labels: "🚀 feature"
body:
- type: textarea
  id: description
  attributes:
    label: Descreva abaixo informações sobre a tarefa
    value: |
      Como [usuario do sistema], 
      Desejo [autenticar no sistema],
      Para [para poder realizar compras]
- type: textarea
  id: details
  attributes:
    label: "Possui detalhes ? Digite aqui toda informação que irá auxiliar no desenvolvimento da tarefa"
  
  
